//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memento.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int RequestTypeId { get; set; }
        public int RequestStatusId { get; set; }
        public int DivisionId { get; set; }
        public System.DateTime DesiredStartDate { get; set; }
        public System.DateTime DesiredExpirationDate { get; set; }
        public int VisitPurposeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual RequestType RequestType { get; set; }
        public virtual User User { get; set; }
        public virtual VisitPurpose VisitPurpose { get; set; }
    }
}
