//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memento.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Visitor = new HashSet<Visitor>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RequestTypeId { get; set; }
        public Nullable<int> RequestStatusId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<System.DateTime> DesiredStartDate { get; set; }
        public Nullable<System.DateTime> DesiredExpirationDate { get; set; }
        public Nullable<int> VisitPurposeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual RequestType RequestType { get; set; }
        public virtual VisitPurpose VisitPurpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visitor> Visitor { get; set; }
    }
}
